language: scala
git:
  depth: 9999
install:
  - git fetch --tags
script:
  - ./bin/runci.sh $CI_TEST
jdk:
  - oraclejdk8
env:
  global:
  - TRAVIS_NODE_VERSION="8"
  matrix:
    - CI_TEST: scalafmt
    - CI_TEST: tests/test

cache:
  directories:
  - $HOME/.sbt/0.13/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache
  - $HOME/.coursier
  - target/repos

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.ivy2/cache -name "*scalafix*.xml" -type f -delete
  - rm -rf $HOME/.ivy2/local
